export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
export const ARTIST_NAME = "ARTIST_NAME";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const TRACK_HISTORY = "TRACK_HISTORY";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const NEW_ARTIST = "NEW_ARTIST";

export const ADMIN_ARTISTS = "ADMIN_ARTISTS";
export const ADMIN_ALBUMS = "ADMIN_ALBUMS";
export const ADMIN_TRACKS = "ADMIN_TRACKS";
